config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  resources :places, param: :uuid
  resources :users, only: [] do
    scope module: :users do
      resources :visited_places, only: %i[index create]
    end
  end
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :recorded_on, presence: true

  scope :default_order, -> { order(recorded_on: :desc, id: :desc) }
end

app/models/place.rb
class Place < ApplicationRecord
  scope :default_order, -> { order(id: :desc) }
  scope :only_today, -> { where(created_at: Time.current.beginning_of_day..Time.current.end_of_day) }

  after_create_commit do
    GenerateAiDescriptionOnPlaceJob.perform_later(place_id: id)
  end

  class << self
    def create_or_find_by_from_google_place!(uuid:)
      place = find_by(uuid:)
      return place if place.present?

      create_from_google_place!(uuid:)
    end
  end

  def update_ai_description!
    client = OpenAI::Client.new
    messages = [
      { role: "system", content: "assistantは旅行ガイドであり、userは旅行者です。assistantはmarkdown記法を使わず、話し言葉のような文章を返します。" },
      { role: "assistant", content: "了解しました！どの国または都市についての情報をお知りになりたいですか？また、どのようなアクティビティに興味がありますか？例えば、文化的な観光、食事、自然の探索などがあります。" },
      { role: "user", content: "#{name}について説明してください。" }
    ]
    response = client.chat(
      parameters: {
        model: "gpt-4o",
        messages:
      }
    )
    update!(ai_description: response.dig("choices", 0, "message", "content"))
  end

  private

  class << self
    def create_from_google_place!(uuid:)
      conn = Faraday.new(
        url: "https://places.googleapis.com/v1/places",
        params: { languageCode: 'ja' },
        headers: {
          'Content-Type' => 'application/json',
          'X-Goog-Api-Key' => Rails.application.credentials.google.api_key,
          'X-Goog-FieldMask' => 'id,displayName,editorialSummary,location,photos'
        }
      ) do |f|
        f.response :json
      end
      body = conn.get(uuid).body
      location = body['location']
      photo = body['photos'].first
      create!(uuid: body['id'],
          name: body['displayName']['text'],
          description: body.dig('editorialSummary', 'text') || '',
          latitude: location['latitude'],
          longitude: location['longitude'],
          photo_url: format_photo_url(photo_name: photo['name']))
    end

    def format_photo_url(photo_name:)
      key = Rails.application.credentials.google.api_key
      max_width_px = 400
      max_height_px = 400
      "https://places.googleapis.com/v1/#{photo_name}/media?key=#{key}&maxWidthPx=#{max_width_px}&maxHeightPx=#{max_height_px}"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :visited_places, dependent: :destroy
  has_many :places, through: :visited_places

  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.update(user_params)
      end
    end

    private

    def user_params_from_auth_hash(auth_hash)
      {
        name: auth_hash.info.name,
        email: auth_hash.info.email,
        image: auth_hash.info.image,
      }
    end
  end

  def x_share_url
    url = Rails.application.routes.url_helpers.user_visited_places_url(id)
    text = places.map { _1.name }.join("、") + "に行きました。"
    "https://x.com/share?url=#{url}&text=#{text}"
  end
end

app/models/visited_place.rb
class VisitedPlace < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user


  def current_user
    return unless (user_id = session[:user_id])

    @current_user ||= User.find_by(id: user_id)
  end

  private

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def authenticate_user!
    redirect_to root_path if current_user.blank?
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def index
    @diaries = current_user.diaries.default_order
  end

  def show
    @diary = current_user.diaries.find(params[:id])
  end

  def new
    @diary = current_user.diaries.build
  end

  def create
    @diary = current_user.diaries.build(diary_params)
    if @diary.save
      redirect_to diaries_path, notice: '日記を作成しました'
    else
      flash.now[:alert] = '日記の作成に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :content, :recorded_on)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[show]

  def show
  end

  private

  def set_place
    @place = Place.create_or_find_by_from_google_place!(uuid: params[:uuid])
  end

  def place_params
    params.require(:place)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if (user = User.find_or_create_from_auth_hash(auth_hash))
      log_in user
    end
    redirect_to root_path
  end

  def destroy
    log_out
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users/visited_places_controller.rb
class Users::VisitedPlacesController < Users::ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    @places = current_user.places.only_today.default_order
  end

  def create
    @place = Place.find(params[:id])
    current_user.visited_places.create!(place_id: @place.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/diaries/index.html.haml
%h1 index
.w-96.mx-auto.overflow-x-auto
  %table.table
    %thead
      %tr
        %th
        %th= Diary.human_attribute_name(:title)
        %th= Diary.human_attribute_name(:content)
        %th= Diary.human_attribute_name(:recorded_on)
    %tbody
      %tr.bg-base-200
        %th 1
        %td Cy Ganderton
        %td Quality Control Specialist
        %td Blue

app/views/diaries/new.html.haml
.diaries__form.w-96.mx-auto
  = simple_form_for @diary, html: { class: 'form-control' } do |f|
    = f.input :title, input_html: { class: 'input input-bordered w-full' }, wrapper: false, label_html: { class: 'label' }
    = f.input :recorded_on, html5: true, input_html: { value: Date.current, class: 'input input-bordered w-full mb-5', type: 'date' }, wrapper: false, label_html: { class: 'label' }
    = f.button :submit, class: 'btn btn-primary'

app/views/diaries/show.html.haml
%h1.text-lg.font-bold.mx-5.mb-5= @diary.title
%ul.timeline.timeline-snap-icon.max-md:timeline-compact.timeline-vertical
  %li
    %hr
    .timeline-middle
      %svg.h-5.w-5{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z", "fill-rule" => "evenodd"}
    .timeline-start.md:text-end.mb-10
      %time.font-mono.italic 1984
      .text-lg.font-black First Macintosh computer
      The Apple Macintosh—later rebranded as the Macintosh 128K—is the original Apple Macintosh personal computer. It played a pivotal role in establishing desktop publishing as a general office function. The motherboard, a 9 in (23 cm) CRT monitor, and a floppy drive were housed in a beige case with integrated carrying handle; it came with a keyboard and single-button mouse.
    %hr
  %li
    %hr
    .timeline-middle
      %svg.h-5.w-5{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z", "fill-rule" => "evenodd"}
    .timeline-end.mb-10
      %time.font-mono.italic 1998
      .text-lg.font-black iMac
      iMac is a family of all-in-one Mac desktop computers designed and built by Apple Inc. It has been the primary part of Apple's consumer desktop offerings since its debut in August 1998, and has evolved through seven distinct forms
    %hr
  %li
    %hr
    .timeline-middle
      %svg.h-5.w-5{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z", "fill-rule" => "evenodd"}
    .timeline-start.md:text-end.mb-10
      %time.font-mono.italic 2001
      .text-lg.font-black iPod
      The iPod is a discontinued series of portable media players and multi-purpose mobile devices designed and marketed by Apple Inc. The first version was released on October 23, 2001, about 8+1⁄2 months after the Macintosh version of iTunes was released. Apple sold an estimated 450 million iPod products as of 2022. Apple discontinued the iPod product line on May 10, 2022. At over 20 years, the iPod brand is the oldest to be discontinued by Apple
    %hr
  %li
    %hr
    .timeline-middle
      %svg.h-5.w-5{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z", "fill-rule" => "evenodd"}
    .timeline-end.mb-10
      %time.font-mono.italic 2007
      .text-lg.font-black iPhone
      iPhone is a line of smartphones produced by Apple Inc. that use Apple's own iOS mobile operating system. The first-generation iPhone was announced by then-Apple CEO Steve Jobs on January 9, 2007. Since then, Apple has annually released new iPhone models and iOS updates. As of November 1, 2018, more than 2.2 billion iPhones had been sold. As of 2022, the iPhone accounts for 15.6% of global smartphone market share
    %hr
  %li
    %hr
    .timeline-middle
      %svg.h-5.w-5{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z", "fill-rule" => "evenodd"}
    .timeline-start.md:text-end.mb-10
      %time.font-mono.italic 2015
      .text-lg.font-black Apple Watch
      The Apple Watch is a line of smartwatches produced by Apple Inc. It incorporates fitness tracking, health-oriented capabilities, and wireless telecommunication, and integrates with iOS and other Apple products and services
    %hr

app/views/home/index.html.haml
.flex.relative
  = turbo_frame_tag 'place-info', class: 'w-[600px]'
  .flex-1{ class: 'h-[1000px] w-[500px]', data: { controller: 'google-map',
                                                   google_map_api_key_value: Rails.application.credentials.google.api_key,
                                                   google_map_map_id_value: Rails.application.credentials.google.map_id } }
  = image_tag 'zunda.png', class: 'absolute w-[400px] end-0'

app/views/layouts/_header.html.haml
.navbar.bg-base-100
  .flex-1
    = link_to '旅行のオトモ', root_path, class: 'btn btn-ghost text-xl'
  .flex-none
  - if current_user
    %ul.menu.menu-menu-vertical.menu-horizontal.rounded-box
      %li= link_to '今日の思い出', user_visited_places_path(current_user)
      %li= link_to "ログアウト", log_out_path, method: :delete
      %li
        %a.flex
          = image_tag current_user.image, class: 'w-[50px] rounded-full'
          %span #{current_user.name}さん
  - else
    = button_to "/auth/google_oauth2", method: :post, data: { turbo: false }, class: 'menu menu-sm' do
      = image_tag "google_auth.svg"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type" }
    %title NeighborTouristGuide
    %meta{ content: "width=device-width,initial-scale=1", name: "viewport" }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  %body
    = render 'layouts/header'
    = yield

app/views/places/_ai_description.html.haml
%div{ data: { controller: 'voicevox' }, id: "ai-description-#{place.id}" }
  - if place.ai_description.present?
    .chat.chat-start
      .chat-image.avator
        .w-10.rounded-full{ class: 'w-[200px]'}
          = image_tag 'zunda-icon.png'
      .chat-bubble{ data: { 'voicevox-target': 'text' } }= place.ai_description
    %button.btn.btn-primary{ type: :button, data: { action: 'voicevox#speechText' } } 説明してもらう

app/views/places/show.turbo_stream.haml
= turbo_stream.update 'place-info' do
  = turbo_stream_from dom_id(@place)
  .card.bg-base-100
    %figure
      %img{ src: @place.photo_url }
    .card-body
      .flex.justify-between.items-center
        %h2.card-title= @place.name
        - if current_user.present? && !current_user.places.where(id: @place).exists?
          = button_to '観光した！', user_visited_places_path(current_user), params: { id: @place.id },
            class: 'btn btn-secondary', id: "visit-button-place-#{@place.id}"
      %p= @place.description
      = render 'ai_description', place: @place

app/views/users/visited_places/create.turbo_stream.haml
= turbo_stream.remove "visit-button-place-#{@place.id}"

app/views/users/visited_places/index.html.haml
%ul.timeline.timeline-vertical
  - @places.each do |place|
    %li
      .timeline-start= l(place.created_at, format: :long)
      .timeline-middle
        %svg.w-5.h-5{fill: "currentColor", viewbox: "0 0 20 20", xmlns: "http://www.w3.org/2000/svg"}
          %path{"clip-rule" => "evenodd", d: "M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z", "fill-rule" => "evenodd"}
      .timeline-end
        .flex.items-center.gap-3
          %p= place.name
          .avatar
            .w-24.rounded-full
              %img{ src: place.photo_url }

  - if current_user.present?
    = link_to current_user.x_share_url, class: 'text-center mt-24 w-100' do
      .flex.items-center.justify-center
        .avatar
          .w-8.rounded-full
            = image_tag 'logo-black.png'
        %span にシェア